### ISSUE TITLE
Redo downsampling readout

### ISSUE THREAD

**Issue by SigridTraegenap** [SigridTraegenap/EEG-Mindball#8]
jetzt: mitteln über gelesenen Daten

**Comment by b3ttin4** [comment]
I wrote code to read (and plot) each data point and not average about them. But I am not sure it improves signal quality. Interpolating the signal seems to help more.

**Comment by SigridTraegenap** [comment]
At least for _1eeg.py I have the impression that our signal is faulty, there is an intrinsic periodicity of the signal and therefore unusual peaks in the FFT
